name: KevinMcNall
favicon: null
layout_spectrum: 0.47546
typography_spectrum: 0.63481
title: Kevin McNall
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#16170f'
    - '#82817d'
    - '#5e5d59'
    - '#afaeaa'
  brandStrength: 0.48705646744929254
  lightness: 0.01708222576417029
  saturation: 0.13970267167314887
  rhythmicContrast: 0.6371438293717802
purpose: []
